stages:
  get_data_stage:
    cmd: 
      - python src/get_data.py || true
    deps: 
      - src/get_data.py
    outs:
      - data/raw/data_raw.csv

  process_data_stage:
    cmd: python src/process_data.py
    deps: 
      - data/raw/data_raw.csv
      - src/process_data.py
    outs:
      - data/raw/data_processed.csv

  train_model_stage:
    cmd: python src/get_data.py
    deps: 
      - model/train.py
      - data/raw/data_processed.csv
    outs:
      - data/metrics/by_region.png
    metrics:
      - data/metrics/metrics.json:
          cache: false
          